name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m')"
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: inux/arm64,linux/amd64
        push: true
        tags:
          - ghcr.io/11mhg/arp-exporter:${{ steps.date.outputs.date }}
          - ghcr.io/11mhg/arp-exporter:${{ github.sha }}
          - ghcr.io/11mhg/arp-exporter:latest
